# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ah84lHE6MperlAGoASJufAvk09RsJkMZ
"""

!pip install biopython

from Bio import SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis

# Índice de instabilidade
def calculate_instability_index(sequence):
    protein_analysis = ProteinAnalysis(sequence)
    instability_index = protein_analysis.instability_index()
    return instability_index

# Carrega as sequências do arquivo FASTA
fasta_file = "Oryza_sativa.fasta"
sequences = []
for record in SeqIO.parse(fasta_file, "fasta"):
    sequences.append((record.id, str(record.seq)))

# Calcula as propriedades físico-químicas
results = []
for seq_id, sequence in sequences:
    protein_analysis = ProteinAnalysis(sequence)
    mass_in_da = protein_analysis.molecular_weight()
    mass_in_kda = mass_in_da / 1000
    instability_index = calculate_instability_index(sequence)
    pI = protein_analysis.isoelectric_point()
    charge = protein_analysis.charge_at_pH(7.4)
    seq_length = len(sequence)

    results.append((seq_id, sequence, mass_in_da, mass_in_kda, instability_index, pI, charge, seq_length))

# Salva os resultados em um único arquivo FASTA
output_file = "Biopython_Oryza.fasta"
with open(output_file, "w") as f:
    for result in results:
        seq_id, sequence, mass_in_da, mass_in_kda, instability_index, pI, charge, seq_length = result
        f.write(f">{seq_id}\n")
        f.write(f"{sequence}\n")

        f.write(f"Comprimento da Sequência: {seq_length}\n\n")
        f.write(f"Peso molecular em Da: {mass_in_da:.2f}\n")
        f.write(f"Peso molecular em kDa: {mass_in_kda:.2f}\n")
        f.write(f"Índice de Instabilidade: {instability_index:.2f}\n")
        f.write(f"Ponto Isoelétrico (pI): {pI:.2f}\n")
        f.write(f"Carga Líquida: {charge:.2f}\n\n")


print("Resultados salvos em", output_file)